# Generated by Django 5.1.4 on 2024-12-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
